'''
PROJECT:     Apiset info
LICENSE:     MIT (https://spdx.org/licenses/MIT)
PURPOSE:     Create hugo pages from the apisets data files
COPYRIGHT:   Copyright 2019 Mark Jansen (mark.jansen@reactos.org)
'''

from pathlib import Path
import re

SCRIPTDIR = Path(__file__).parent
DEFAULTDATADIR = Path(SCRIPTDIR).parent / 'data'
DEFAULTCONTENTDIR = Path(SCRIPTDIR).parent / 'content'


HUGO_TEMPLATE = """
---
# This file is auto-generated by a script
title: "{version}"
slug: "{version}"
weight: {weight}
---

{{{{< {template} >}}}}

"""



def natural_key(string_):
    """See http://www.codinghorror.com/blog/archives/001018.html"""
    return [int(s) if s.isdigit() else s for s in re.split(r'(\d+)', string_)]

def sorted_datafiles(dirname):
    sources = []
    for filename in dirname.glob('*.json'):
        sources.append(filename.stem)
    return sorted(sources, key=natural_key)


def write_templates(data_dir, template_dir, template):
    sources = sorted_datafiles(data_dir)
    weight = 1
    template_dir.mkdir(parents=True, exist_ok=True)
    for source in sources:
        filename = '_autogenerated_{:03d}.md'.format(weight)
        with open(template_dir / filename, 'w') as markdown_file:
            markdown_file.write(HUGO_TEMPLATE.format(version=source, weight=weight, template=template))
        weight += 1


def pages_from_schemas(apisetschema_data_dir, schema_content_dir):
    print('Creating pages for apisetschemas')
    # Clean apisetschema pages
    for filename in schema_content_dir.glob('_autogenerated_*.md'):
        filename.unlink()

    # Create new apisetschema pages
    write_templates(apisetschema_data_dir, schema_content_dir, 'apisetschema')
    print('Done')

#def pages_from_apisets(apisets_data_dir, apisets_content_dir):
#    print('Creating pages for apisets')
#    # Clean apisets pages
#    for filename in apisets_content_dir.glob('**/_autogenerated_*.md'):
#        filename.unlink()
#
#    #for version_dir in apisets_data_dir.iterdir():
#    #    if version_dir.is_dir():
#    #        #print(version_dir)
#    #        write_templates(version_dir, apisets_content_dir / version_dir.name, 'apiset')
#
#    print('Done')



if __name__ == '__main__':
    pages_from_schemas(DEFAULTDATADIR / 'apisetschema', DEFAULTCONTENTDIR / 'apisetschemas')
    #pages_from_apisets(DEFAULTDATADIR / 'apisets', DEFAULTCONTENTDIR / 'apisets')

